### ISSUE TITLE
AMBEO SoundBar Error - object does not support the context manager protocol

### ISSUE THREAD

**Issue by cyberax2023** [faizpuru/ha-ambeo_soundbar#15]
Dear friend!
I've got an error for my AMBEO Soundbar:

Log:
2024-11-04 00:06:17.642 ERROR (MainThread) [custom_components.ambeo_soundbar.api.impl.generic_api] HTTP request exception with url: http://192.168.1.33:80/api/getData?path=settings:/system/serialNumber&roles=@all&_nocache=1730667977642. Exception: 'Timeout' object does not support the context manager protocol

UI:
![image](https://github.com/user-attachments/assets/dab6b309-b342-4c69-be52-54f49cf02d3a)

**Comment by faizpuru** [comment]
Hello,

Thank you for your feedback!

To help diagnose the issue, could you please confirm the version of the AMBEO Soundbar you’re using?

Additionally, could you try opening the following URLs in a browser on the same local network as the soundbar and provide the result for each URL?

1. [Serial Number
](http://192.168.1.33/api/getData?path=settings:/system/serialNumber&roles=@all&_nocache=1730667977642)

2. [Product Name](http://192.168.1.33/api/getData?path=settings:/system/productName&roles=@all&_nocache=1730667977642)


3. [Firmware Version
](http://192.168.1.33/api/getData?path=ui:settings/firmwareUpdate/currentV&roles=@all&_nocache=1730667977642)


This information will help me understand the current configuration and identify any potential compatibility issues or updates needed.

Thank you very much

**Comment by cyberax2023** [comment]
I have AMBEO MAX
After last update everything works fine now!
THank you!
