### ISSUE TITLE
AMBEO soundbar mini

### ISSUE THREAD

**Issue by tuupos** [faizpuru/ha-ambeo_soundbar#18]
I have a soundbar mini and I am willing to help (in the little spare time that i have)  

File "/config/custom_components/ambeo_soundbar/api/factory.py", line 29, in create_api
    raise ValueError(f"Unsupported model : {model}")
ValueError: Unsupported model : AMBEO Soundbar Mini

In the previous version of this integration it worked.

how can I help?

**Comment by faizpuru** [comment]
Everything was working fine ?
Lights, sound, control, night mode, ambeo mode, etc ?

If it's the case, ambeo plus and mini share the same api.

**Comment by tuupos** [comment]
Just tested. Never used the lights control but it works in the sennheiser app and also from the integration. Light bar, ambeo logo. And codecs lights van be turned in and off through integration. 
Select input works. Play/pause. Volume control everything works as expected. 

Mini working


But.... Only in first version. 

In the last version the above error occurs.
"Mini not supported". Can you fix this?

Can i be of any further support?

**Comment by faizpuru** [comment]
Cool, I will add the mini support tomorrow :)

**Comment by faizpuru** [comment]
This should be fixed in the latest version (1.0.5). Feel free to give me feedback.

**Comment by tuupos** [comment]
Indeed fixed ! Thanks 1
