### ISSUE TITLE
Feature Request: Subwoofer Settings

### ISSUE THREAD

**Issue by adrianjost** [faizpuru/ha-ambeo_soundbar#21]
It would be nice if I could enable/disable the subwoofer from within Homeassistant. I'm mainly interested in toggling it on or off, but controlling it's intensity would also be cool 

# WebUI
For reference what the ambeo plus web UI allows
<img width="891" alt="image" src="https://github.com/user-attachments/assets/8aee30b7-2c44-4e7a-b340-2f57bee107fb">

# API Calls from `ambeo.local` of an Ambeo Plus Soundbar
### Read Status

**Request:** 
`http://ambeo.local/api/getData?path=ui%3A%2Fsettings%2Fsubwoofer%2Fenabled&roles=%40all&_nocache=1731407752010`
<img width="759" alt="image" src="https://github.com/user-attachments/assets/6f897c61-2350-4627-99ac-1301a7d772f7">

**Response:**
<img width="863" alt="image" src="https://github.com/user-attachments/assets/d3e924dc-e825-47f6-8751-0dd5d2e0a000">

### Set Status

**Enable Subwoofer:**
`http://ambeo.local/api/setData?path=ui%3A%2Fsettings%2Fsubwoofer%2Fenabled&role=value&value=%7B%22type%22%3A%22bool_%22%2C%22bool_%22%3Atrue%7D&_nocache=1731407214298`
<img width="589" alt="image" src="https://github.com/user-attachments/assets/532f79e8-955a-400c-a16f-3cb4d131a0ac">
<img width="296" alt="image" src="https://github.com/user-attachments/assets/b360302d-e0f4-4a50-91f1-693a89d60e90">

**Disable Subwoofer:**
`http://ambeo.local/api/setData?path=ui%3A%2Fsettings%2Fsubwoofer%2Fenabled&role=value&value=%7B%22type%22%3A%22bool_%22%2C%22bool_%22%3Afalse%7D&_nocache=1731407425580`
<img width="592" alt="image" src="https://github.com/user-attachments/assets/3055685d-5f43-4389-9d84-20e25148a524">
<img width="418" alt="image" src="https://github.com/user-attachments/assets/3177c250-118f-496a-b58d-143d79a16e24">

### Read Status

**Request:** 
`http://ambeo.local/api/getData?path=ui%3A%2Fsettings%2Fsubwoofer%2Fvolume&roles=%40all&_nocache=1731407752010`
<img width="759" alt="image" src="https://github.com/user-attachments/assets/6f897c61-2350-4627-99ac-1301a7d772f7">
<img width="285" alt="image" src="https://github.com/user-attachments/assets/76fd210f-c11b-4dd5-9fdd-489d40c2edcf">

**Response:**
<img width="712" alt="image" src="https://github.com/user-attachments/assets/66180372-c3e0-4fb2-912f-d914bc661a06">

### Set Status

Range is from `-10` to `10` in integer steps.
`http://ambeo.local/api/setData?path=ui%3A%2Fsettings%2Fsubwoofer%2Fvolume&role=value&value=%7B%22type%22%3A%22double_%22%2C%22double_%22%3A5%7D&_nocache=1731407574333`
<img width="593" alt="image" src="https://github.com/user-attachments/assets/8c307bfd-82e7-4b66-9d14-c19353e54532">
<img width="289" alt="image" src="https://github.com/user-attachments/assets/092cf800-0c4b-4ded-a284-fe21bf36e102">

**Comment by faizpuru** [comment]
Great news! 🎉 Subwoofer features are now available for testing in version 1.0.6-beta.

To try it out:
1. Go to HACS
2. Open the Ambeo Soundbar integration
3. Click "Redownload"
4. Select version 1.0.6-beta
5. Restart Home Assistant

Please let me know if everything works as expected with your subwoofer! Your feedback will help ensure the feature is working correctly before the stable release. 🙏

**Comment by adrianjost** [comment]
Wow, that was fast 😍🚀
Unfortunately after following your steps and even fully reinstalling the plugin and setting it up again I do not see any new entities.

**Comment by faizpuru** [comment]
Oops, there was a typo on one url. You can try 1.0.6-beta2.
If it's not working, please give me the result this url:
[http://ambeo.local/api/getData?path=settings%3A%2Fpopcorn%2Fsubwoofer%2Flist&roles=value&_nocache=1731450519512](http://ambeo.local/api/getData?path=settings%3A%2Fpopcorn%2Fsubwoofer%2Flist&roles=value&_nocache=1731450519512)

**Comment by adrianjost** [comment]
It's now working as expected 🎉
All added features are working great and are very responsive. Even the sync back of changes made on the Soundbar itself are quickly visible in HA. 
Thank you!
