### ISSUE TITLE
features available but not in readme.md

### ISSUE THREAD

**Issue by tuupos** [faizpuru/ha-ambeo_soundbar#25]
Features in the integration like: switch.ambeo_soundbar_mini_sound_feedback and light.ambeo_soundbar_mini_ambeo_logo

are working but not mentioned or documented  in README.md.

for example: what does switch.ambeo_soundbar_mini_sound_feedback do? open up the mic?

thanks in advance

**Comment by faizpuru** [comment]
The readme has been updated
