### ISSUE TITLE
Google Cast doesnt appear under the sources

### ISSUE THREAD

**Issue by trullock** [faizpuru/ha-ambeo_soundbar#27]
And an interesting bug, which is almost certainly not this integrations fault, but maybe we can get to the bottom of it together:

1) If I Google Cast to my Plus using Youtube Music on a Google Pixel 7, in both the Sennheiser App and this integration; it shows as Playing. However this integration doesn't show its "Google Cast" as the source, its blank. Sennheiser App does report it's Google Cast thats playing, although theres no track-id or similar showing (should there be?)

2) If I play from Radio Browser in HA, then both this integration and Sennheiser app report it as Idle/not playing. This says Idle, Sennheiser shows the Play control button (as opposed to pause). Consequently the Ambeo turns off after 17 mins of presumably what it thinks is inactivity.

2b) This is the same behaviour if I use the Media Browser in HA to play a "local" mp3. Its "Idle" even though its actaully playing the music.

How is it that HA isnt convincing the Ambeo that its playing, even though it does play? I know thats way out of scope here but hoping collective intelligence can crack it, otherwise the product is useless to me, as it turns off when im streaming from HA!

**Comment by trullock** [comment]
Google Cast doesn't appear under the Sennheiser App's Input Sources dropdown, so presumably thats the issue here. Firmware bug?

**Comment by trullock** [comment]
Music Assistant Server doesnt have this issue, so its something to do with HA's media player casting

**Comment by faizpuru** [comment]
Hi Andrew,

Thank you for reporting these issues. Just released version 1.0.7 with bug fixes:
- fixed the source display issue for AirPlay and Google Cast in the source dropdown.

The second issue seems to be related to Home Assistant's Google Cast integration indeed.
